services:
  - type: web
    name: drm-bot-2
    plan: free
    env: python
    dockerfilePath: Dockerfile
    repo: https://github.com/NARUJAT/DRM-Bot-2
    branch: main
    autoDeploy: false
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      #- key: WEBHOOK
        #sync: false
      - key: PORT
        value: 8000  # Default port value, update if needed
