services:
  - type: web
    name: drm-bot-2
    runtime: docker
    dockerfilePath: Dockerfile
    startCommand: "python3 -m main"
    envVars:
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: BOT_TOKEN
        sync: false
      - key: RENDER_EXTERNAL_HOSTNAME
        sync: false
